### ISSUE TITLE
对 2-word2vec 这块疑惑

### ISSUE THREAD

**Issue by 340StarObserver** [coderSkyChen/2016CCF_BDCI_Sougou#1]
在 2-word2vec/main.py 中 ：
jieba_train_cut.csv 和 jieba_test_cut.csv 是第一个模块中分词的结果，
那么， jieba_total_cut.csv这个文件是哪来的？

**Comment by coderSkyChen** [comment]
是train和test拼起来的，总的文本。

**Comment by 340StarObserver** [comment]
嗯嗯谢谢~，特征工程跑通了，另外问下最后训练的时候需要多大内存吖，8g的不够>_<

发自我的vivo智能手机

陈潇凯 <notifications@github.com>编写：
