### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'train.csv'

### ISSUE THREAD

**Issue by 1046214092** [coderSkyChen/2016CCF_BDCI_Sougou#2]
jieba_cut_fliter.py 这个报错。'train.csv'这个文件在哪里下载。

**Comment by coderSkyChen** [comment]
这个文件泛指用于分词的纯文本文件，格式是一行一个文本（一个单位），具体到这里，是把sogou训练集中的所有纯文本（去除标签，id等等）集合成trian.csv
