### ISSUE TITLE
请问S-TFIWF中的不同类别是怎么获得的？

### ISSUE THREAD

**Issue by JackieQiang** [coderSkyChen/2016CCF_BDCI_Sougou#3]
不是太懂得不同的类如何得到。

**Comment by coderSkyChen** [comment]
不好意思回复的有些晚了。
训练集中的文档是有标签的，例如，对于性别属性来说，分为：男、女、unknown，去掉未知的话，所有的文档在性别的角度可以被分为两类，然后就可以统计某个单词在某个类中出现的次数了。“类别”是针对某一个属性来说的。
